### ISSUE TITLE
High memory and CPU consuming

### ISSUE THREAD

**Issue by nlpsuge** [GSConnect/gnome-shell-extension-gsconnect#1189]
> ***ATTENTION**: GSConnect only supports the latest, stable version of GNOME. We are no longer accepting bug reports for previous versions.*

**Describe the bug**
When enable this extension, OS freezes about less than one second per about ten more seconds. It's even worse when move cursor quickly.

And high memory and CPU consuming gracefully.
![image](https://user-images.githubusercontent.com/2271720/138128089-3e1ddc38-d10f-4af3-8612-e9236cd8db50.png)

Disable this extension and wait some time the occupied resources (memory and CPU) will be released, which could take quite a few time. Restarting gnome-shell via `r in Alt+F2` can cause occupied resources to be released immediately. 

**Steps To Reproduce:**

1. Enable this extension
2. Open some apps and wait this situation

**Expected behavior**

I can use this extension normally, don't consume so much resources and freeze the OS.

**Support Log**

Please generate a support log ([Instructions](../wiki/Help#generate-support-log)) and paste any messages related to this issue between the two ``` lines below.

```

```

**System Details (please complete the following information):**

 - **GSConnect version:** [e.g. 35, 36, ... (displayed in the GSConnect "About" window)]
 47
   - **Installed from:** [e.g. GNOME Extensions Website, GitHub, Package Manager, ...]
   GNOME Extensions Website
 - **GNOME/Shell version:** [e.g. 3.36, ...]
 40.4
 - **Distro/Release:** [e.g. Ubuntu 18.04, Fedora 29, Arch, ...]
Fedora 34
**GSConnect environment (if applicable):**

 - **Paired Device(s):** [e.g. Galaxy Note 8, Pixel 2, Honor 9, ...]
 - **KDE Connect app version:** [e.g. 1.12.7]
 - **Plugin(s):** [if the issue only occurs when using certain plugin(s)]

**Additional Notes:**
Note that: Another account on the same OS does not have this issue. I only enable it when needed on this account. Maybe there is miss-configuration or  broken environment ...?

Any advice?

**Comment by Stugeh** [comment]
also happens on PopOS 21.04. Over the course of afew hours the memory usage of my gnome shell climbed to 12GB.

**Comment by daniellandau** [comment]
@Stugeh You wouldn't happen to live near Helsinki and be willing to debug in person?

**Comment by Stugeh** [comment]
> @Stugeh You wouldn't happen to live near Helsinki and be willing to debug in person?

No, not particularly. I also have no experience with memory leaks in garbage collected languages so I'm not sure how much of a help I'd be in the first place.

**Comment by daniellandau** [comment]
That's too bad... My main problem is that I simply haven't been able to reproduce this issue.

**Comment by nlpsuge** [comment]
Hi daniellandau, 

This issue still persists on Fedora 35.

 Any idea how to debug this issue?

**Comment by augugusto** [comment]
i also have this issue on fedora 35. I notice it more often when I'm watching Netflix or YouTube where it's very obvious when something freezes. i think it takes a while to start happening

**Comment by nemoitis** [comment]
I just found this issue on Manjaro Qonos 21.2.0. I've tracked `gnome-shell` memory usage as far as 2GB+.

**Comment by augugusto** [comment]
Since the devs can't find the issue maybe we can help. Whoever is i treated let's try disabling all kde connect plugins. If that reduces memory usage we can then start enabling one each day until we find the one causing the issue

**Comment by teh404guy** [comment]
can confirm, extension takes too much ram gradually in active mode
when the tray icon disappears it gets laggier
putting the extension in inactive mode (not disable the entire extension) still hogs ram but doesnt gradually get worse
have to restart gnome to clear memory

**Comment by andyholmes** [comment]
You can try the fix in #1233 if you like, that may help.

**Comment by augugusto** [comment]
I have just installed the master version (commit c84588a0f9685adb9b4bf6012bbfc716ccc3a3ad)
I will report back if i have any issues.

**Comment by augugusto** [comment]
after two hours of uptime I'm at 4.6GB and 0% CPU. so I would say that worked.

Keep in mind that I shut down my computer every night so I won't test large multi week periods of uptime like most of you do

**Comment by mkwork** [comment]
Still reproducing on master and ubuntu 21.10 with gnome-shell 40.4. Is there any way to profile it?

**Comment by mratmartinez** [comment]
Any news on when are we going to get commit c84588a0f9685adb9b4bf6012bbfc716ccc3a3ad in a new version available in gnome-extensions.org?

If that solves the problem, I'd like to have it. I can't install the master branch since I'm using GNOME 40.4

**Comment by nlpsuge** [comment]
I don't encounter this issue for at least three months. And I don't know how and when it's got fixed in my case.

**Comment by andyholmes** [comment]
There's no news. A new release will be uploaded when the current maintainer has time available.

Note that there is no guarantee that the fix will be backported for older versions of GNOME Shell.

**Comment by daniellandau** [comment]
The memory leak fix has been uploaded for shell versions 3.36, 3.38, 41 and 42. There's no guarantee that it was the only memory/cpu issue but I'll close this for now until new reports of issues still affecting people
