### ISSUE TITLE
Remote Input doesn't work with urdu language.

### ISSUE THREAD

**Issue by Bhallu-pk** [GSConnect/gnome-shell-extension-gsconnect#1208]
GSConnect can't seem to accept urdu character when using remote input. It seem to work when i uninstall the extension and install KDE Connect from the store. I can type perfectly in english.

**Steps To Reproduce:**

1. Go to Remote Input in the KDE Connect Mobile app.
2. Click on Keyboard icon and switch your keyboard language to Urdu lanugae.
3. Try to type anything in the keyboard.
4. Nothing will get typed into the input field.

**Expected behavior**

Remote Input should be able to type urdu language.

**Support Log**

```

GSConnect: 45 (user)
GJS:       16702
Session:   x11
OS:        Pop!_OS 21.04
--------------------------------------------------------------------------------
-- Journal begins at Sun 2021-10-17 23:26:55 PKT, ends at Thu 2021-11-18 19:26:34 PKT. --
Nov 18 19:26:03 dbus-daemon[1924]: [session uid=1000 pid=1924] Activating service name='org.gnome.gedit' requested by ':1.126' (uid=1000 pid=5666 comm="gjs /home/arbaz/.local/share/gnome-shell/extension" label="unconfined")
Nov 18 19:26:03 dbus-daemon[1924]: [session uid=1000 pid=1924] Successfully activated service 'org.gnome.gedit'
Nov 18 19:26:03 gnome-shell[2997]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x38000f8
Nov 18 19:26:23 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:31 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:31 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:31 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:31 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:31 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:31 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:31 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:31 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:31 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:32 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:32 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:32 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:32 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:32 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:32 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:32 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:32 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:32 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:33 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:33 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:33 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:33 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:33 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:33 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:33 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:33 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:33 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:34 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:34 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:34 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:34 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:34 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
Nov 18 19:26:34 /usr/libexec/gdm-x-session[1968]: [xkb] BOGUS LENGTH in SetMap: expected 268 got 1292
```

**System Details:**

 - **GSConnect version:** 45
   - **Installed from:** GNOME Extensions Website
 - **GNOME/Shell version:** 3.38.4
 - **Distro/Release:** POP!_OS 21.04

**GSConnect environment:**

 - **Paired Device(s):** Honor 6x, Huawei P9 Lite
 - **KDE Connect app version:** 1.18.0

**Additional Notes:**
When i install the KDE Connect app in the distro and pair to it and type urdu using remote keyboard. I can type in urdu. It just doesn't work with GSConnect extension.

**Comment by andyholmes** [comment]
This probably won't ever work on X11 in GSConnect. The options are limited for simulating input events, and as you can see from the log xkb is choking up on unicode characters. Sorry about that :/

**Comment by BHALUU** [comment]
> This probably won't ever work on X11 in GSConnect. The options are limited for simulating input events, and as you can see from the log xkb is choking up on unicode characters. Sorry about that :/

Would it work on wayland?

**Comment by andyholmes** [comment]
I believe that it should. If it doesn't work in Wayland, where we use the RemoteDesktop interface, I would expect it is a bug in either GSConnect or one of GNOME Shell's libraries that can and should be fixed.

These days with X11 we often run into situations where you just can't do something you should be able to, because the design just didn't account for the need.

**Comment by BHALUU** [comment]
Hey @andyholmes, I have switched to fedora 35 which uses wayland by default but the problem still exists. I still can't seem to type in urdu.

This is the log file in fedora 35.
```
GSConnect: 47 (user)
GJS:       17000
Session:   wayland
OS:        Fedora Linux 35 (Workstation Edition)
--------------------------------------------------------------------------------
Jan 20 22:27:10 systemd[1550]: dbus-:1.2-org.gnome.gedit@0.service: Consumed 6.219s CPU time.
Jan 20 22:27:18 systemd[1550]: Started Application launched by gnome-shell.
Jan 20 22:27:18 systemd[1550]: Started Application launched by gnome-shell.
Jan 20 22:27:20 audit: BPF prog-id=96 op=LOAD
Jan 20 22:27:20 audit: BPF prog-id=97 op=LOAD
Jan 20 22:27:20 systemd[1]: Starting Hostname Service...
Jan 20 22:27:20 systemd[1]: Started Hostname Service.
Jan 20 22:27:20 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 20 22:27:25 systemd[1550]: app-gnome-gnome\x2dwifi\x2dpanel-19124.scope: Consumed 1.324s CPU time.
Jan 20 22:27:30 systemd[1550]: Started dbus-:1.2-org.gnome.gedit@1.service.
Jan 20 22:27:36 gnome-shell[1707]: No keycode found for keyval 10006af in current group
Jan 20 22:27:36 gnome-shell[1707]: No keycode found for keyval 10006af in current group
Jan 20 22:27:36 gnome-shell[1707]: No keycode found for keyval 10006d2 in current group
Jan 20 22:27:36 gnome-shell[1707]: No keycode found for keyval 10006d2 in current group
Jan 20 22:27:36 gnome-shell[1707]: No keycode found for keyval 1000679 in current group
Jan 20 22:27:36 gnome-shell[1707]: No keycode found for keyval 1000679 in current group
Jan 20 22:27:37 gnome-shell[1707]: No keycode found for keyval 10006be in current group
Jan 20 22:27:37 gnome-shell[1707]: No keycode found for keyval 10006be in current group
Jan 20 22:27:38 gnome-shell[1707]: No keycode found for keyval 5c1 in current group
Jan 20 22:27:38 gnome-shell[1707]: No keycode found for keyval 5c1 in current group
Jan 20 22:27:39 gnome-shell[1707]: No keycode found for keyval 1000691 in current group
Jan 20 22:27:39 gnome-shell[1707]: No keycode found for keyval 1000691 in current group
Jan 20 22:27:39 gnome-shell[1707]: No keycode found for keyval 5e1 in current group
Jan 20 22:27:39 gnome-shell[1707]: No keycode found for keyval 5e1 in current group
Jan 20 22:27:39 gnome-shell[1707]: No keycode found for keyval 5e1 in current group
Jan 20 22:27:39 gnome-shell[1707]: No keycode found for keyval 5e1 in current group
```

**Comment by andyholmes** [comment]
Do you have urdu set as your input source language in GNOME? It seems like Mutter tries to [lookup the keycode](https://github.com/GNOME/mutter/blob/main/src/backends/native/meta-virtual-input-device-native.c#L467-L512) (hardware) for the keysym (actual glyph) when it attempts to simulate the input.

**Comment by BHALUU** [comment]
@andyholmes yes urdu is set as one of the input sources in gnome.

**Comment by andyholmes** [comment]
Is it the primary or selected input method when you try to send this character? I don't have an urdu keyboard on my phone so it's hard to test this, but it seems like Mutter will only input characters from the current keymap.

If you're sure that the correct input source is selected when you're sending these keypresses you should probably [open an issue in Mutter](https://gitlab.gnome.org/GNOME/mutter/-/issues), since that's where these errors are coming from.

**Comment by BHALUU** [comment]
Thanks @andyholmes. I have figured it out. I am quite new to the linux world. So I am not quite familiar with linux way right now. So, Everytime I have to type in urdu i have to switch the input source to urdu.

I am now able to type in urdu but there is still a problem. There are some letters that are not registered when i press them. The review log for them is the same as before. Should i open an issue about this in mutter?

I am using Gboard - The Google Keyboard. If you are using android, you can use the google keyboard to switch between multiple languages.

**Comment by andyholmes** [comment]
Can you provide a log that includes the debug packets, so we can be sure the correct characters are being passed and which keysym is being sent to mutter? The should look something like this:

```js
{
    "id": 0,
    "type": "kdeconnect.mousepad.request",
    "body": {
        "key": "خ"
    }
}
```

**Comment by BHALUU** [comment]
where can i find this log file?

**Comment by andyholmes** [comment]
Follow the steps to [Generate a Support Log](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Help#generate-support-log). Specifically you **must not** close the dialog until you have finished.

**Comment by BHALUU** [comment]
Is this it?

```

GSConnect: 47 (user)
GJS:       17000
Session:   wayland
OS:        Fedora Linux 35 (Workstation Edition)
--------------------------------------------------------------------------------
Jan 21 00:59:02 wpa_supplicant[933]: wlp3s0: CTRL-EVENT-SIGNAL-CHANGE above=0 signal=-75 noise=-95 txrate=135000
Jan 21 00:59:08 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 3
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 3
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 00:59:08 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 3
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 3
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 00:59:09 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642708748797,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "پ"
                                                               }
                                                             }
Jan 21 00:59:09 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/components/input.js:_ensureAdapter:472]: "Creating Mutter RemoteDesktop session"
Jan 21 00:59:09 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/components/input.js:pressKey:611]: this._session is null
                                                             pressKey@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/input.js:611:13
                                                             _handleInput@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mousepad.js:189:33
                                                             handlePacket@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mousepad.js:133:22
                                                             handlePacket@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:415:25
                                                             _readLoop@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:339:22
                                                             async*setChannel@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:320:18
                                                             _onChannel@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:225:20
                                                             channel@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                                                             _onIncomingChannel@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                                                             Async*@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Jan 21 00:59:11 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642708750341,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "گ"
                                                               }
                                                             }
Jan 21 00:59:12 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642708751436,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ڈ"
                                                               }
                                                             }
Jan 21 00:59:13 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642708752344,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ے"
                                                               }
                                                             }
Jan 21 00:59:13 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642708752866,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "پ"
                                                               }
                                                             }
Jan 21 00:59:14 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 3
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 3
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 00:59:14 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 3
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 3
                                                                   }
                                                                 }
                                                               }
                                                             }
```

**Comment by andyholmes** [comment]
Yes that's it, but there are no errors from gnome-shell or mutter in that one.

Can you provide one that has both so I can see which characters are being rejected and what keyvals are being sent to mutter?

**Comment by BHALUU** [comment]
```

GSConnect: 47 (user)
GJS:       17000
Session:   wayland
OS:        Fedora Linux 35 (Workstation Edition)
--------------------------------------------------------------------------------
Jan 21 01:21:07 systemd[26078]: dbus-:1.2-org.gnome.gedit@15.service: Consumed 5.869s CPU time.
Jan 21 01:21:15 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710074550,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ط"
                                                               }
                                                             }
Jan 21 01:21:15 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/components/input.js:_ensureAdapter:472]: "Creating Mutter RemoteDesktop session"
Jan 21 01:21:15 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/components/input.js:pressKey:611]: this._session is null
                                                             pressKey@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/components/input.js:611:13
                                                             _handleInput@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mousepad.js:189:33
                                                             handlePacket@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/plugins/mousepad.js:133:22
                                                             handlePacket@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:415:25
                                                             _readLoop@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:339:22
                                                             async*setChannel@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/device.js:320:18
                                                             _onChannel@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/manager.js:225:20
                                                             channel@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/core.js:445:19
                                                             _onIncomingChannel@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/backends/lan.js:216:18
                                                             Async*@/home/arbaz/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:727:17
Jan 21 01:21:15 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710075120,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ظ"
                                                               }
                                                             }
Jan 21 01:21:15 gnome-shell[26219]: No keycode found for keyval 5d8 in current group
Jan 21 01:21:15 gnome-shell[26219]: No keycode found for keyval 5d8 in current group
Jan 21 01:21:16 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710075668,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ئ"
                                                               }
                                                             }
Jan 21 01:21:16 gnome-shell[26219]: No keycode found for keyval 5c6 in current group
Jan 21 01:21:16 gnome-shell[26219]: No keycode found for keyval 5c6 in current group
Jan 21 01:21:17 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710076306,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ح"
                                                               }
                                                             }
Jan 21 01:21:17 gnome-shell[26219]: No keycode found for keyval 5cd in current group
Jan 21 01:21:17 gnome-shell[26219]: No keycode found for keyval 5cd in current group
Jan 21 01:21:17 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710076854,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ث"
                                                               }
                                                             }
Jan 21 01:21:17 gnome-shell[26219]: No keycode found for keyval 5cb in current group
Jan 21 01:21:17 gnome-shell[26219]: No keycode found for keyval 5cb in current group
Jan 21 01:21:17 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 01:21:17 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 01:21:18 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710077369,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ٹ"
                                                               }
                                                             }
Jan 21 01:21:18 gnome-shell[26219]: No keycode found for keyval 1000679 in current group
Jan 21 01:21:18 gnome-shell[26219]: No keycode found for keyval 1000679 in current group
Jan 21 01:21:18 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710077854,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ڑ"
                                                               }
                                                             }
Jan 21 01:21:18 gnome-shell[26219]: No keycode found for keyval 1000691 in current group
Jan 21 01:21:18 gnome-shell[26219]: No keycode found for keyval 1000691 in current group
Jan 21 01:21:19 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710078328,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "غ"
                                                               }
                                                             }
Jan 21 01:21:19 gnome-shell[26219]: No keycode found for keyval 5da in current group
Jan 21 01:21:19 gnome-shell[26219]: No keycode found for keyval 5da in current group
Jan 21 01:21:19 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710078815,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ص"
                                                               }
                                                             }
Jan 21 01:21:19 gnome-shell[26219]: No keycode found for keyval 5d5 in current group
Jan 21 01:21:19 gnome-shell[26219]: No keycode found for keyval 5d5 in current group
Jan 21 01:21:19 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710079257,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ض"
                                                               }
                                                             }
Jan 21 01:21:19 gnome-shell[26219]: No keycode found for keyval 5d6 in current group
Jan 21 01:21:19 gnome-shell[26219]: No keycode found for keyval 5d6 in current group
Jan 21 01:21:20 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710079976,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "پ"
                                                               }
                                                             }
Jan 21 01:21:20 gnome-shell[26219]: No keycode found for keyval 100067e in current group
Jan 21 01:21:20 gnome-shell[26219]: No keycode found for keyval 100067e in current group
Jan 21 01:21:21 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710080447,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ہ"
                                                               }
                                                             }
Jan 21 01:21:21 gnome-shell[26219]: No keycode found for keyval 10006c1 in current group
Jan 21 01:21:21 gnome-shell[26219]: No keycode found for keyval 10006c1 in current group
Jan 21 01:21:21 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 01:21:21 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 01:21:21 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710080954,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ی"
                                                               }
                                                             }
Jan 21 01:21:21 gnome-shell[26219]: No keycode found for keyval 10006cc in current group
Jan 21 01:21:21 gnome-shell[26219]: No keycode found for keyval 10006cc in current group
Jan 21 01:21:22 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710081504,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ء"
                                                               }
                                                             }
Jan 21 01:21:22 gnome-shell[26219]: No keycode found for keyval 5c1 in current group
Jan 21 01:21:22 gnome-shell[26219]: No keycode found for keyval 5c1 in current group
Jan 21 01:21:23 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710083130,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ٔ"
                                                               }
                                                             }
Jan 21 01:21:23 gnome-shell[26219]: No keycode found for keyval 1000654 in current group
Jan 21 01:21:23 gnome-shell[26219]: No keycode found for keyval 1000654 in current group
Jan 21 01:21:24 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710083788,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ے"
                                                               }
                                                             }
Jan 21 01:21:24 gnome-shell[26219]: No keycode found for keyval 10006d2 in current group
Jan 21 01:21:24 gnome-shell[26219]: No keycode found for keyval 10006d2 in current group
Jan 21 01:21:26 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710085329,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ۓ"
                                                               }
                                                             }
Jan 21 01:21:26 gnome-shell[26219]: No keycode found for keyval 10006d3 in current group
Jan 21 01:21:26 gnome-shell[26219]: No keycode found for keyval 10006d3 in current group
Jan 21 01:21:27 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710086341,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ت"
                                                               }
                                                             }
Jan 21 01:21:27 gnome-shell[26219]: No keycode found for keyval 5ca in current group
Jan 21 01:21:27 gnome-shell[26219]: No keycode found for keyval 5ca in current group
Jan 21 01:21:27 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 01:21:27 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 01:21:27 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710086894,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ر"
                                                               }
                                                             }
Jan 21 01:21:27 gnome-shell[26219]: No keycode found for keyval 5d1 in current group
Jan 21 01:21:27 gnome-shell[26219]: No keycode found for keyval 5d1 in current group
Jan 21 01:21:28 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710087773,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ر"
                                                               }
                                                             }
Jan 21 01:21:28 gnome-shell[26219]: No keycode found for keyval 5d1 in current group
Jan 21 01:21:28 gnome-shell[26219]: No keycode found for keyval 5d1 in current group
Jan 21 01:21:29 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710088430,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ع"
                                                               }
                                                             }
Jan 21 01:21:29 gnome-shell[26219]: No keycode found for keyval 5d9 in current group
Jan 21 01:21:29 gnome-shell[26219]: No keycode found for keyval 5d9 in current group
Jan 21 01:21:29 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710088993,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "و"
                                                               }
                                                             }
Jan 21 01:21:29 gnome-shell[26219]: No keycode found for keyval 5e8 in current group
Jan 21 01:21:29 gnome-shell[26219]: No keycode found for keyval 5e8 in current group
Jan 21 01:21:30 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710089834,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ق"
                                                               }
                                                             }
Jan 21 01:21:30 gnome-shell[26219]: No keycode found for keyval 5e2 in current group
Jan 21 01:21:30 gnome-shell[26219]: No keycode found for keyval 5e2 in current group
Jan 21 01:21:31 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710090721,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ل"
                                                               }
                                                             }
Jan 21 01:21:31 gnome-shell[26219]: No keycode found for keyval 5e4 in current group
Jan 21 01:21:31 gnome-shell[26219]: No keycode found for keyval 5e4 in current group
Jan 21 01:21:32 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710091484,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ک"
                                                               }
                                                             }
Jan 21 01:21:32 gnome-shell[26219]: No keycode found for keyval 10006a9 in current group
Jan 21 01:21:32 gnome-shell[26219]: No keycode found for keyval 10006a9 in current group
Jan 21 01:21:32 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710092203,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ج"
                                                               }
                                                             }
Jan 21 01:21:32 gnome-shell[26219]: No keycode found for keyval 5cc in current group
Jan 21 01:21:32 gnome-shell[26219]: No keycode found for keyval 5cc in current group
Jan 21 01:21:33 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 01:21:33 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 01:21:33 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710092888,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ھ"
                                                               }
                                                             }
Jan 21 01:21:33 gnome-shell[26219]: No keycode found for keyval 10006be in current group
Jan 21 01:21:33 gnome-shell[26219]: No keycode found for keyval 10006be in current group
Jan 21 01:21:34 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710093526,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "گ"
                                                               }
                                                             }
Jan 21 01:21:34 gnome-shell[26219]: No keycode found for keyval 10006af in current group
Jan 21 01:21:34 gnome-shell[26219]: No keycode found for keyval 10006af in current group
Jan 21 01:21:34 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710094179,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ف"
                                                               }
                                                             }
Jan 21 01:21:34 gnome-shell[26219]: No keycode found for keyval 5e1 in current group
Jan 21 01:21:34 gnome-shell[26219]: No keycode found for keyval 5e1 in current group
Jan 21 01:21:35 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710095014,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ف"
                                                               }
                                                             }
Jan 21 01:21:35 gnome-shell[26219]: No keycode found for keyval 5e1 in current group
Jan 21 01:21:35 gnome-shell[26219]: No keycode found for keyval 5e1 in current group
Jan 21 01:21:36 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710095560,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "د"
                                                               }
                                                             }
Jan 21 01:21:36 gnome-shell[26219]: No keycode found for keyval 5cf in current group
Jan 21 01:21:36 gnome-shell[26219]: No keycode found for keyval 5cf in current group
Jan 21 01:21:37 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710096353,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ڈ"
                                                               }
                                                             }
Jan 21 01:21:37 gnome-shell[26219]: No keycode found for keyval 1000688 in current group
Jan 21 01:21:37 gnome-shell[26219]: No keycode found for keyval 1000688 in current group
Jan 21 01:21:37 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710097079,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "س"
                                                               }
                                                             }
Jan 21 01:21:37 gnome-shell[26219]: No keycode found for keyval 5d3 in current group
Jan 21 01:21:37 gnome-shell[26219]: No keycode found for keyval 5d3 in current group
Jan 21 01:21:38 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710097543,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ا"
                                                               }
                                                             }
Jan 21 01:21:38 gnome-shell[26219]: No keycode found for keyval 5c7 in current group
Jan 21 01:21:38 gnome-shell[26219]: No keycode found for keyval 5c7 in current group
Jan 21 01:21:39 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710098501,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "م"
                                                               }
                                                             }
Jan 21 01:21:39 gnome-shell[26219]: No keycode found for keyval 5e5 in current group
Jan 21 01:21:39 gnome-shell[26219]: No keycode found for keyval 5e5 in current group
Jan 21 01:21:39 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 3
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 01:21:39 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 3
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 3
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 01:21:40 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710100075,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "؟"
                                                               }
                                                             }
Jan 21 01:21:40 gnome-shell[26219]: No keycode found for keyval 5bf in current group
Jan 21 01:21:40 gnome-shell[26219]: No keycode found for keyval 5bf in current group
Jan 21 01:21:41 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710101127,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ن"
                                                               }
                                                             }
Jan 21 01:21:41 gnome-shell[26219]: No keycode found for keyval 5e6 in current group
Jan 21 01:21:41 gnome-shell[26219]: No keycode found for keyval 5e6 in current group
Jan 21 01:21:42 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710101746,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ں"
                                                               }
                                                             }
Jan 21 01:21:42 gnome-shell[26219]: No keycode found for keyval 10006ba in current group
Jan 21 01:21:42 gnome-shell[26219]: No keycode found for keyval 10006ba in current group
Jan 21 01:21:43 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710102297,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ن"
                                                               }
                                                             }
Jan 21 01:21:43 gnome-shell[26219]: No keycode found for keyval 5e6 in current group
Jan 21 01:21:43 gnome-shell[26219]: No keycode found for keyval 5e6 in current group
Jan 21 01:21:43 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710102970,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ب"
                                                               }
                                                             }
Jan 21 01:21:43 gnome-shell[26219]: No keycode found for keyval 5c8 in current group
Jan 21 01:21:43 gnome-shell[26219]: No keycode found for keyval 5c8 in current group
Jan 21 01:21:44 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710104058,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ب"
                                                               }
                                                             }
Jan 21 01:21:44 gnome-shell[26219]: No keycode found for keyval 5c8 in current group
Jan 21 01:21:44 gnome-shell[26219]: No keycode found for keyval 5c8 in current group
Jan 21 01:21:45 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710104825,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "چ"
                                                               }
                                                             }
Jan 21 01:21:45 gnome-shell[26219]: No keycode found for keyval 1000686 in current group
Jan 21 01:21:45 gnome-shell[26219]: No keycode found for keyval 1000686 in current group
Jan 21 01:21:46 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710105660,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "خ"
                                                               }
                                                             }
Jan 21 01:21:46 gnome-shell[26219]: No keycode found for keyval 5ce in current group
Jan 21 01:21:46 gnome-shell[26219]: No keycode found for keyval 5ce in current group
Jan 21 01:21:47 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710106336,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ش"
                                                               }
                                                             }
Jan 21 01:21:47 gnome-shell[26219]: No keycode found for keyval 5d4 in current group
Jan 21 01:21:47 gnome-shell[26219]: No keycode found for keyval 5d4 in current group
Jan 21 01:21:47 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710106859,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ز"
                                                               }
                                                             }
Jan 21 01:21:47 gnome-shell[26219]: No keycode found for keyval 5d2 in current group
Jan 21 01:21:47 gnome-shell[26219]: No keycode found for keyval 5d2 in current group
Jan 21 01:21:48 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642710107388,
                                                               "type": "kdeconnect.mousepad.request",
                                                               "body": {
                                                                 "key": "ذ"
                                                               }
                                                             }
Jan 21 01:21:48 gnome-shell[26219]: No keycode found for keyval 5d0 in current group
Jan 21 01:21:48 gnome-shell[26219]: No keycode found for keyval 5d0 in current group
Jan 21 01:21:48 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   }
                                                                 }
                                                               }
                                                             }
Jan 21 01:21:48 org.gnome.Shell.Extensions.GSConnect[26625]: [/service/device.js:_readLoop:338]: Honor 6x: {
                                                               "id": 1642703215184,
                                                               "type": "kdeconnect.connectivity_report",
                                                               "body": {
                                                                 "signalStrengths": {
                                                                   "0": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   },
                                                                   "1": {
                                                                     "networkType": "UMTS",
                                                                     "signalStrength": 4
                                                                   }
                                                                 }
                                                               }
                                                             }
```

**Comment by andyholmes** [comment]
Thanks, that was with the correct input method selected?

If so, that looks like we are interpreting the characters properly and passing the correct keysyms to Mutter. So you should open an issue in Mutter for this.

**Comment by BHALUU** [comment]
What should the issue be about? I mean what should i say to the mutter team specifically?

**Comment by andyholmes** [comment]
Something like this:

**Title:** RemoteDesktop fails to handle keyvals from the urdu alphabet
**Body:**

When passing keyvals like `0x5c8` for the "چ" character, gnome-shell prints errors like this:

```
Jan 21 01:21:43 gnome-shell[26219]: No keycode found for keyval 5c8 in current group
```

The downstream issue is in GSConnect at https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1208

**Comment by BHALUU** [comment]
Ok I will open the issue. Thanks for helping out.

**Comment by andyholmes** [comment]
Thanks for reporting, I will follow the upstream issue and help if I can.

**Comment by bilelmoussaoui** [comment]
It would be nice if people affected by this issue could test the following patch https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/748 and report back in the PR so we can merge the fix.

**Comment by andyholmes** [comment]
I will build and give this a shot tonight, thanks for the ping back :)
