### ISSUE TITLE
Gnome 43 support

### ISSUE THREAD

**Issue by pled** [GSConnect/gnome-shell-extension-gsconnect#1476]
Gnome 43 starts being deployed, for example on Debian Testing "bookworm". This extension is now disabled being incompatible.

**Steps To Reproduce:**

Run Debian 12 "bookworm" with latest updates.

**Comment by pled** [comment]
Thank you for the quick answer. 
Note I did a search with "(is:issue is:open "Gnome 43") but strangely the #1475 did not appear in results... :(

**Comment by steve-todorov** [comment]
No worries! Feel free to checkout the PR - it's working fine for me but the more testers the better :)

**Comment by andyholmes** [comment]
Fixed in #1475

**Comment by daniellandau** [comment]
Next weekend

**Comment by chinmayghule** [comment]
GSConnect in Gnome extensions still shows as "Outdated". How do I make it work?

![image](https://user-images.githubusercontent.com/56955520/199206192-668312f4-7aab-45aa-9e53-ec10751af464.png)

**Comment by greenship24** [comment]
> GSConnect in Gnome extensions still shows as "Outdated". How do I make it work?
> 
> ![image](https://user-images.githubusercontent.com/56955520/199206192-668312f4-7aab-45aa-9e53-ec10751af464.png)

I would assume you have gnome-shell-extension-gsconnect installed. Try uninstalling it then installing the version from the webpage.

**Comment by KTibow** [comment]
not sure if this has been reported already but the icon doesn't seem to work
![image](https://user-images.githubusercontent.com/10727862/205517433-3d72872f-62f3-48e1-9008-fd026690abde.png)

**Comment by KTibow** [comment]
nvm #1509 #1506

**Comment by ferdnyc** [comment]
I think we can safely unpin this now. We actually DON'T support GNOME 43 anymore, as the code has moved on to requiring GNOME 44. :grin:
