### ISSUE TITLE
Gsconnect release with gnome 45 support

### ISSUE THREAD

**Issue by Armatik** [GSConnect/gnome-shell-extension-gsconnect#1680]
### Describe your request

Good time of day. Please tell me when to expect the official release of gsconnect with gnome 45 support?

### GSConnect version

55

### Installed from

GNOME Extensions website

**Comment by crashbit666** [comment]
You can see a thread about gnome 45 support here:

https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1665

**Comment by Armatik** [comment]
> You can see a thread about gnome 45 support here:
> 
> #1665 #1679

Yes, I read the thread, how can I take part in testing and are the approximate release dates known?

**Comment by andyholmes** [comment]
There are no ETAs, release will happen when the release maintainer has time.

There are instructions in the Wiki for [Installing from Nightly Build](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-nightly-build).

**Comment by ivanjx** [comment]
i tried installing from nightly build but now it says "Waiting for service..."

**Comment by andyholmes** [comment]
Looks like the executable bit is being lost on `service/daemon.js` and `gsconnect-preferences` since https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1526.

This should fix it for now:

```sh
$ chmod +x ~/.local/share/gnome-shell/extensions/gsconnect\@andyholmes.github.io/{gsconnect-preferences,service/daemon.js}
```

**Comment by ivanjx** [comment]
unfortunately it still does not work.

```
Oct 16 09:15:43 dbus-daemon[2665]: [session uid=1000 pid=2665] Activating service name='org.gnome.Shell.Extensions.GSConnect' requested by ':1.95' (uid=1000 pid=3920 comm="/usr/bin/gapplication action org.gnome.Shell.Exten" label="unconfined")
Oct 16 09:15:43 systemd[2622]: Started app-gnome-org.gnome.Shell.Extensions.GSConnect.Preferences-3920.scope - Application launched by gnome-shell.
Oct 16 09:15:43 gjs[3926]: GFileInfo created without standard::symlink-target
Oct 16 09:15:43 gjs[3926]: file ../../../gio/gfileinfo.c: line 2062 (g_file_info_get_symlink_target): should not be reached
Oct 16 09:15:43 gjs[3926]: JS ERROR: Error: Requiring EBook, version none: Typelib file for namespace 'EBook' (any version) not found
                           @/home/xx/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/utils/setup.js:17:34
                           @/home/xx/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:42:16
Oct 16 09:15:43 gjs[3926]: Script /home/xx/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js threw an exception
Oct 16 09:15:43 dbus-daemon[2665]: [session uid=1000 pid=2665] Activated service 'org.gnome.Shell.Extensions.GSConnect' failed: Process org.gnome.Shell.Extensions.GSConnect exited with status 1
Oct 16 09:15:43 org.gnome.Shell.Extensions.GSConnect.Preferences.desktop[3920]: error sending ActivateAction message to application: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.Shell.Extensions.GSConnect exited with status 1
```

im not sure if it is because i upgraded from 23.04 but if nothing works then i would reinstall my ubuntu.

**Comment by jonathanhirschman** [comment]
> unfortunately it still does not work.

Had the same problem; try installing the optional components mentioned at the bottom of the zip/nightly install instructions to fix.

**Comment by ivanjx** [comment]
thanks @jonathanhirschman 
to be exact i think the problem is related to these packages not being installed (at least according to my error logs):
`gir1.2-ebook-1.2`, `gir1.2-ebookcontacts-1.2`, `gir1.2-edataserver-1.2`

would be great if the docs is updated to install these packages as requirements

**Comment by trailjeep** [comment]
> thanks @jonathanhirschman to be exact i think the problem is related to these packages not being installed (at least according to my error logs): `gir1.2-ebook-1.2`, `gir1.2-ebookcontacts-1.2`, `gir1.2-edataserver-1.2`

Thank you @ivanjx! 
openSUSE pkgs = `typelib-1_0-EBook-1_2` `typelib-1_0-EBookContacts-1_2` `typelib-1_0-EDataServer-1_2`

**Comment by sidevesh** [comment]
Isee the new release with Gnome 45 support is out, this can be closed
