### ISSUE TITLE
GSConnect not working on Gnome 48

### ISSUE THREAD

**Issue by niltonperimneto** [GSConnect/gnome-shell-extension-gsconnect#1967]
### Describe the bug

I was using the beta and RC versions of Gnome 48 on  Arch Linux and the extension had no problem whatsoever, however it seems that after the stable version released it borked the extension. In the Extension Manager it reports that the version 58 isn't compatible with version 48 of Gnome.

It seems that it is a problem with the metadata in the Gnome Extension website that only reports up to the version 47.

### GSConnect version

58

### Installed from

GNOME Extensions website

### GNOME Shell version

48

### Linux distribution/release

Arch

### Paired device(s)

Samsung S22

### Support log

```plain text

```

**Comment by niltonperimneto** [comment]
If I build it myself it works fine, and I checket the metadata of the package in the extensions.gnome.org and it is indeed outdated and doesn't work currently with the version 48

**Comment by develroo** [comment]
I am getting this error which is unusually cryptic 

![Image](https://github.com/user-attachments/assets/fd38ec7e-8dfa-4635-9c19-8603a87e40ee)

**Comment by BlackDex** [comment]
I tried building from git, it does install, and seems to start without Gnome errors.
But it isn't working. It states the following.

![Image](https://github.com/user-attachments/assets/dcc8171d-2095-4346-b017-9e205eb8e409)

And this is shown in the logs:

```
Mar 22 17:01:00 gnome-shell[3979]: GSConnect: Gio.IOErrorEnum: Timeout was reached
                                   
                                   Stack trace:
                                     start/</<@file:///home/blackdex/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/utils/remote.js:460:51
                                     @resource:///org/gnome/shell/ui/init.js:21:20
                                     
```

**Comment by simdlldev** [comment]
I have solved changing this line in `~/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js`
from this:
line 12: `import * as Calendar from 'resource:///org/gnome/shell/ui/calendar.js';`
to : `import * as Calendar from 'resource:///org/gnome/shell/ui/messageList.js';`
I have followed the official istructions to update extensions: https://gjs.guide/extensions/upgrading/gnome-shell-48.html

**Comment by guillaume-uH57J9** [comment]
The import change mentioned by @simdlldev, plus a version tweak in `metadata.json`, allows the extension to run again on my system, which is running gnome-shell 48~rc-2

**Comment by DamianUntapped** [comment]
I'm getting the same error as @develroo above. It also doesn't show in the panel anymore.

![Image](https://github.com/user-attachments/assets/b7eff87e-2a53-499c-938f-4cdc65d9b535)

I'm going to try what @simdlldev did.

**Comment by simdlldev** [comment]
@DamianUntapped 
You have to look to this path: `~/**.local/share/gnome-shell/extensions**/gsconnect@andyholmes.github.io/shell/notification.js`
Also try to add 48 in `metadata.json`

**Comment by DamianUntapped** [comment]
@simdlldev thanks for the response. 

Not seeing it in that path either. 

![Image](https://github.com/user-attachments/assets/3138cff1-604b-448f-9ffc-118ddf6d8eb4)

Where is metadata.json located?

**Comment by nozwock** [comment]
@DamianUntapped 
No need to mess with it.

The issue is fixed on latest `main`.

Just [build from source](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-git), and install with `gnome-extensions install --force gsconnect@andyholmes.github.io.zip`

**Comment by develroo** [comment]
> [@DamianUntapped](https://github.com/DamianUntapped) No need to mess with it.
> 
> The issue is fixed on latest `main`.
> 
> Just [build from source](https://github.com/GSConnect/gnome-shell-extension-gsconnect/wiki/Installation#install-from-git), and install with `gnome-extensions install --force gsconnect@andyholmes.github.io.zip`
> 
> But I'm including my build here in case someone non-technical stumbles into this issue. [gsconnect@andyholmes.github.io.zip](https://github.com/user-attachments/files/19405502/gsconnect%40andyholmes.github.io.zip)

This is fine as a workaround. But if this is the only issue, shouldn't it be then rolled into a new version that works for everyone?  Are the gnome-extension not built automatically like flatpaks?

**Comment by somepaulo** [comment]
Still getting the same `Waiting for service...` error as @BlackDex with latest `main` build and Gnome 48 on Arch.  
The mobile settings window does not open from the quick settings menu. I have to go to extension settings to open it.
I have two errors in the logs:
```sh
JS ERROR: TypeError: this._removeDevice is not a function
vfunc_handle_local_options@file:///home/somepaulo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:690:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
```
and
```sh
JS ERROR: TypeError: this.manager is undefined
vfunc_dbus_unregister@file:///home/somepaulo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:309:9
vfunc_handle_local_options@file:///home/somepaulo/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:690:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
```

**Comment by BlackDex** [comment]
Arch here too.

**Comment by DamianUntapped** [comment]
I am also on Arch.

**Comment by piglesias1** [comment]
Thanks @simdlldev for the information. It worked for me. I'm using Arch, Gnome 48 and GSConnect from AUR (gnome-shell-extension-gsconnect).

@DamianUntapped, not sure if you already fixed, but if you have similar configuration like mine, using the AUR package, try to edit the following files:

/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/metadata.json - Line 6

from ` "shell-version": [ "46", "47" ],`
to `"shell-version": [ "46", "47", "48" ],`

/usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js - Line 12

from `import * as Calendar from 'resource:///org/gnome/shell/ui/calendar.js';`
to `import * as Calendar from 'resource:///org/gnome/shell/ui/messageList.js';`

See the [post](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1967#issuecomment-2745402371) above from @simdlldev.

**Comment by DamianUntapped** [comment]
@piglesias1 

Thanks a ton! That worked!

For any other non-linux savvy people out there like me, the metadata.json & notification.js files are probably restricted to root access which you probably don't have. So, double clicking those files to edit them won't work. So, I figured out that you need to use the terminal and a command like "sudo gedit /usr/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/shell/notification.js" to open and edit the file (don't use the quotes). sudo for root permission and gedit is just a text editor, so if you don't have gedit, you'll have to use some other editor, like nano (or whatever you have installed).

I'm assuming in a future update to GSConnect, these changes, or something else, will fix this and we won't need to do this anymore.

**Comment by lnguyen4** [comment]
Fix described by @piglesias1 post above seems to be working for me and I use the official extension installation method - the "extension" app. I am on EndeavourOS.

So, I edited the metadata.json and notification.js files, whose directory locations, for me, are just `home/dir/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io`.

**Comment by piglesias1** [comment]
That's great news, @DamianUntapped! I'm sorry about not explaining about the permission issue. As a rule of thumb, normal users have permissions to edit files inside their home directory. So, any edit outside home directory, needs root permission and then you can use `sudo` (you need to have /etc/sudoers file configured).

And about future updates, it's common to happen about the metadata.json when upgrading Gnome version. It depends on the developer to release a fix and the package maintainer to update in the package repo, and then become compatible with the new Gnome version. But other issues, like this one including Gnome break changes, it can happen, but it's less frequent.

**Comment by SalvatoreNoschese** [comment]
> Thanks [@simdlldev](https://github.com/simdlldev) for the information. It worked for me. I'm using Arch, Gnome 48 and GSConnect from AUR (gnome-shell-extension-gsconnect).
> 
> [@DamianUntapped](https://github.com/DamianUntapped), not sure if you already fixed, but if you have similar configuration like mine, using the AUR package, try to edit the following files:
> 
> /usr/share/gnome-shell/extensions/[gsconnect@andyholmes.github.io](mailto:gsconnect@andyholmes.github.io)/metadata.json - Line 6
> 
> from ` "shell-version": [ "46", "47" ],` to `"shell-version": [ "46", "47", "48" ],`
> 
> /usr/share/gnome-shell/extensions/[gsconnect@andyholmes.github.io](mailto:gsconnect@andyholmes.github.io)/shell/notification.js - Line 12
> 
> from `import * as Calendar from 'resource:///org/gnome/shell/ui/calendar.js';` to `import * as Calendar from 'resource:///org/gnome/shell/ui/messageList.js';`
> 
> See the [post](https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1967#issuecomment-2745402371) above from [@simdlldev](https://github.com/simdlldev).

ty, work also here (Arch linux, installed from website).

Path is: `/home/***/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io`

**Comment by prahal** [comment]
If you use gsconnect git I believe without https://github.com/GSConnect/gnome-shell-extension-gsconnect/pull/1963 you might not be able to pair and even keep existing pairs. There is a bug in the device migration code in git.
Editing latest release with the above changes you posted should be good to go.

**Comment by nozwock** [comment]
So, right now, building from main doesn't really work, although the extension won't crash and error out in the extension manager, it does seemingly fails to pair up or recognize devices. Seems like it's due to using of a different protocol version which I saw being mentioned in some PR. 

What does work is just modifying the `v58` build to fix the `Calendar` import and adding gnome `48` to the metadata file, like done here https://github.com/GSConnect/gnome-shell-extension-gsconnect/issues/1967#issuecomment-2755049513

**Comment by juanmah** [comment]
> What does work is just modifying the v58 build to fix the Calendar import and adding gnome 48 to the metadata file, like done here #1967 (comment)

Doing that, I get  `Waiting for service...` 

> Still getting the same `Waiting for service...` error as [@BlackDex](https://github.com/BlackDex) with latest `main` build and Gnome 48 on Arch. The mobile settings window does not open from the quick settings menu. I have to go to extension settings to open it. I have two errors in the logs:

**Comment by BlackDex** [comment]
I just tried the `wget` way, and that worked for me.
I did a full clean/uninstall of the extension first, reboot, installed the modified extension zip, logged-out and back in again.
And it worked.

Though i did also removed the pairing and re-paired after that too.
